POST http://localhost:3333/events
Content-Type: application/json

{
  "title": "Event unique",
  "details": "This is my event",
  "maximumAttendees": 1
}

### 

POST http://localhost:3333/events/3f881bd2-1bef-435e-a086-de2ff9bed4aa/attendees
Content-Type: application/json

{
  "name": "Alice",
  "email": "alice2@teste.com"
}

### 
GET http://localhost:3333/events/3f881bd2-1bef-435e-a086-de2ff9bed4aa


###
GET http://localhost:3333/attendees/1/badge


###
GET http://localhost:3333/attendees/1/check-in